// Generates src/data.ts from data/calendar.json, the canonical month-length
// table exported from the go-bs reference package by tools/go-reference.
//
// Usage: bun run generate
//
// This is a maintainer tool. Package users never need it: src/data.ts is
// committed, and the published package contains no JSON.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

interface CalendarFile {
  source: string;
  minYear: number;
  maxYear: number;
  years: Record<string, number[]>;
}

const root = new URL("..", import.meta.url);
const input = fileURLToPath(new URL("data/calendar.json", root));
const output = fileURLToPath(new URL("src/data.ts", root));

const calendar = JSON.parse(readFileSync(input, "utf8")) as CalendarFile;

const rows: string[] = [];
for (let year = calendar.minYear; year <= calendar.maxYear; year++) {
  const months = calendar.years[String(year)];
  if (!months || months.length !== 12) {
    throw new Error(`data/calendar.json: year ${year} must have exactly 12 months`);
  }
  for (const days of months) {
    if (!Number.isInteger(days) || days < 29 || days > 32) {
      throw new Error(`data/calendar.json: year ${year} has an implausible month length ${days}`);
    }
  }
  rows.push(`  [${months.join(", ")}], // ${year}`);
}
if (Object.keys(calendar.years).length !== rows.length) {
  throw new Error("data/calendar.json: contains years outside minYear..maxYear");
}

const source = `// Code generated by scripts/generate-data.ts from data/calendar.json. DO NOT EDIT.
//
// Source: ${calendar.source} (see docs/calendar-data.md).
// Regenerate with: bun run generate

/** The number of days in each of the 12 months of one Bikram Sambat year. */
export type MonthLengths = readonly [
  number, number, number, number, number, number,
  number, number, number, number, number, number,
];

/** The first BS year in CALENDAR_DATA. */
export const DATA_MIN_YEAR = ${calendar.minYear};

/** The last BS year in CALENDAR_DATA. */
export const DATA_MAX_YEAR = ${calendar.maxYear};

/**
 * The number of days in each Bikram Sambat month, one row per year from
 * DATA_MIN_YEAR to DATA_MAX_YEAR inclusive. Row 0 is DATA_MIN_YEAR.
 */
export const CALENDAR_DATA: readonly MonthLengths[] = [
${rows.join("\n")}
];
`;

writeFileSync(output, source);
console.log(`wrote ${output} (${rows.length} years)`);
