// Command go-reference exports the calendar dataset and a set of
// compatibility fixtures from the published Go package
// github.com/suprimkhatri77/go-bs, which is the reference specification for
// this TypeScript package.
//
// It is a maintainer tool. Normal users and the npm test suite never run it:
// its outputs are committed, and the TypeScript tests read them as static
// JSON. Re-run it only when moving to a new go-bs version (update the version
// in go.mod and goBSVersion below together):
//
//	cd tools/go-reference && go run . -root ../..
//	bun run generate
//
// Outputs (relative to -root):
//
//	data/calendar.json               canonical month-length table
//	tests/fixtures/go-conversions.json  every supported BS date and Go's AD/weekday/day-of-year for it
//	tests/fixtures/go-cases.json        edge cases: validation, parsing, formatting, arithmetic, out-of-range, age
//	tests/fixtures/go-months.json       every supported BS month: calendar grid, start/end, next/previous month
package main

import (
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
	"time"

	bs "github.com/suprimkhatri77/go-bs"
)

// goBSVersion must match the go-bs version required in go.mod. It's recorded
// in every output file so a fixture can always be traced to the exact Go
// release it came from.
const goBSVersion = "v0.6.1"

const source = "github.com/suprimkhatri77/go-bs@" + goBSVersion

func main() {
	root := flag.String("root", "../..", "bikram-sambat-ts repository root to write outputs into")
	flag.Parse()

	writeJSON(filepath.Join(*root, "data", "calendar.json"), calendar())
	writeConversions(filepath.Join(*root, "tests", "fixtures", "go-conversions.json"), conversions())
	writeJSON(filepath.Join(*root, "tests", "fixtures", "go-cases.json"), cases())
	m := months()
	writeRows(filepath.Join(*root, "tests", "fixtures", "go-months.json"), m.Comment, m.Source, "months", m.Months)
}

// errKind maps a go-bs sentinel error to the short name the TypeScript tests
// use. An empty string means "no error".
func errKind(err error) string {
	switch {
	case err == nil:
		return ""
	case errors.Is(err, bs.ErrInvalidYear):
		return "year"
	case errors.Is(err, bs.ErrInvalidMonth):
		return "month"
	case errors.Is(err, bs.ErrInvalidDay):
		return "day"
	case errors.Is(err, bs.ErrInvalidFormat):
		return "format"
	case errors.Is(err, bs.ErrOutOfRange):
		return "outOfRange"
	case errors.Is(err, bs.ErrInvalidDateOrder):
		return "dateOrder"
	default:
		log.Fatalf("unexpected error kind: %v", err)
		return ""
	}
}

func adString(t time.Time) string { return t.Format("2006-01-02") }

func must[T any](v T, err error) T {
	if err != nil {
		log.Fatal(err)
	}
	return v
}

type calendarFile struct {
	Comment string           `json:"$comment"`
	Source  string           `json:"source"`
	MinYear int              `json:"minYear"`
	MaxYear int              `json:"maxYear"`
	Years   map[string][]int `json:"years"`
}

func calendar() calendarFile {
	f := calendarFile{
		Comment: "Generated by tools/go-reference from the go-bs package. Do not edit by hand; see docs/calendar-data.md.",
		Source:  source,
		MinYear: bs.MinBSYear,
		MaxYear: bs.MaxBSYear,
		Years:   map[string][]int{},
	}
	for year := bs.MinBSYear; year <= bs.MaxBSYear; year++ {
		months := make([]int, 12)
		for month := 1; month <= 12; month++ {
			months[month-1] = must(bs.DaysInMonth(year, month))
		}
		f.Years[fmt.Sprint(year)] = months
	}
	return f
}

type conversionsFile struct {
	Comment string `json:"$comment"`
	Source  string `json:"source"`
	Count   int    `json:"count"`
	// Days holds one [bs, ad, weekday, dayOfYear] tuple per supported BS
	// date, in chronological order.
	Days [][4]any `json:"days"`
}

func conversions() conversionsFile {
	f := conversionsFile{
		Comment: "Generated by tools/go-reference. Each entry: [BS date, AD date from go-bs BSToAD, weekday (0 = Sunday), day of BS year].",
		Source:  source,
	}
	for year := bs.MinBSYear; year <= bs.MaxBSYear; year++ {
		for month := 1; month <= 12; month++ {
			days := must(bs.DaysInMonth(year, month))
			for day := 1; day <= days; day++ {
				d := must(bs.NewDate(year, month, day))
				ad := must(bs.BSToAD(d))
				weekday := must(d.DayOfWeek())
				doy := must(d.DayOfYear())
				f.Days = append(f.Days, [4]any{d.String(), adString(ad), int(weekday), doy})
			}
		}
	}
	f.Count = len(f.Days)
	return f
}

type validationCase struct {
	Year  int    `json:"year"`
	Month int    `json:"month"`
	Day   int    `json:"day"`
	Valid bool   `json:"valid"`
	Error string `json:"error"`
}

type adCase struct {
	AD    string `json:"ad"`
	BS    string `json:"bs"`
	Error string `json:"error"`
}

type parseCase struct {
	Input string `json:"input"`
	BS    string `json:"bs"`
	Error string `json:"error"`
}

type formatCase struct {
	BS     string `json:"bs"`
	Layout string `json:"layout"`
	Output string `json:"output"`
}

type addDaysCase struct {
	BS     string `json:"bs"`
	Days   int    `json:"days"`
	Result string `json:"result"`
	Error  string `json:"error"`
}

type betweenCase struct {
	From string `json:"from"`
	To   string `json:"to"`
	Days int    `json:"days"`
}

type digitsCase struct {
	Input  string `json:"input"`
	Nepali string `json:"nepali"`
	ASCII  string `json:"ascii"`
}

type monthNameCase struct {
	Month  int    `json:"month"`
	Name   string `json:"name"`
	Nepali string `json:"nepali"`
	Error  string `json:"error"`
}

type casesFile struct {
	Comment     string           `json:"$comment"`
	Source      string           `json:"source"`
	MinAD       string           `json:"minAD"`
	MaxAD       string           `json:"maxAD"`
	Validation  []validationCase `json:"validation"`
	ADToBS      []adCase         `json:"adToBs"`
	Parse       []parseCase      `json:"parse"`
	Format      []formatCase     `json:"format"`
	AddDays     []addDaysCase    `json:"addDays"`
	DaysBetween []betweenCase    `json:"daysBetween"`
	Digits      []digitsCase     `json:"digits"`
	MonthNames  []monthNameCase  `json:"monthNames"`
	YearBounds  []yearBoundsCase `json:"yearBounds"`
	MonthErrors []monthErrorCase `json:"monthErrors"`
	Age         []ageCase        `json:"age"`
}

type yearBoundsCase struct {
	Year  int    `json:"year"`
	Start string `json:"start"`
	End   string `json:"end"`
	Error string `json:"error"`
}

// monthErrorCase records the error go-bs returns from the month-based
// helpers for a year/month that isn't supported.
type monthErrorCase struct {
	Year               int    `json:"year"`
	Month              int    `json:"month"`
	StartOfMonth       string `json:"startOfMonth"`
	EndOfMonth         string `json:"endOfMonth"`
	FirstWeekday       string `json:"firstWeekday"`
	WeeksInMonth       string `json:"weeksInMonth"`
	MonthCalendarError string `json:"monthCalendar"`
}

type ageCase struct {
	Birth  string `json:"birth"`
	Today  string `json:"today"`
	Years  int    `json:"years"`
	Months int    `json:"months"`
	Days   int    `json:"days"`
	Error  string `json:"error"`
}

func cases() casesFile {
	lastDay := must(bs.DaysInMonth(bs.MaxBSYear, 12))
	minAD := must(bs.BSToAD(must(bs.NewDate(bs.MinBSYear, 1, 1))))
	maxAD := must(bs.BSToAD(must(bs.NewDate(bs.MaxBSYear, 12, lastDay))))

	f := casesFile{
		Comment: "Generated by tools/go-reference. Expected values are whatever go-bs returns; error is one of year, month, day, format, outOfRange, or empty for success.",
		Source:  source,
		MinAD:   adString(minAD),
		MaxAD:   adString(maxAD),
	}

	// Validation: every (month, day) shape around the edges of a few years,
	// including out-of-range years, plus the day just past each month's end.
	for _, year := range []int{bs.MinBSYear - 1, bs.MinBSYear, 2000, 2080, 2083, bs.MaxBSYear, bs.MaxBSYear + 1, 0, -2080} {
		for _, month := range []int{-1, 0, 1, 6, 12, 13} {
			for _, day := range []int{-5, 0, 1, 28, 29, 30, 31, 32, 33} {
				_, err := bs.NewDate(year, month, day)
				f.Validation = append(f.Validation, validationCase{year, month, day, bs.IsValid(year, month, day), errKind(err)})
			}
		}
	}

	// AD -> BS at and just beyond both ends of the range, and at every BS
	// new year's day and its eve.
	adDates := []time.Time{minAD.AddDate(0, 0, -1), minAD, maxAD, maxAD.AddDate(0, 0, 1),
		time.Date(1900, 1, 1, 0, 0, 0, 0, time.UTC), time.Date(2100, 1, 1, 0, 0, 0, 0, time.UTC)}
	for year := bs.MinBSYear; year <= bs.MaxBSYear; year++ {
		newYear := must(bs.BSToAD(must(bs.NewDate(year, 1, 1))))
		adDates = append(adDates, newYear.AddDate(0, 0, -1), newYear)
	}
	for _, ad := range adDates {
		d, err := bs.ADToBS(ad)
		c := adCase{AD: adString(ad), Error: errKind(err)}
		if err == nil {
			c.BS = d.String()
		}
		f.ADToBS = append(f.ADToBS, c)
	}

	for _, s := range []string{
		"2083-06-06", "1979-01-01", "2100-12-31", "", "2083/06/06", "2083-6-6", "2083-06-06x",
		" 2083-06-06", "2083-06-06\n", "83-06-06", "20830-06-06", "2083-13-01", "2083-00-01",
		"1978-01-01", "2101-01-01", "2083-06-32", "2083-06-00", "२०८३-०६-०६", "2083-06-3a", "+083-06-06",
	} {
		d, err := bs.Parse(s)
		c := parseCase{Input: s, Error: errKind(err)}
		if err == nil {
			c.BS = d.String()
		}
		f.Parse = append(f.Parse, c)
	}

	layouts := []string{
		"YYYY-MM-DD", "YY-M-D", "MMMM D, YYYY", "dddd, MMMM D, YYYY", "YYYY/MM/DD", "ddd DD MMM",
		"D-M-YYYY", "DD-MM-YYYY", "no tokens here", "", "YYYYY", "MMMMM", "ddddd", "Day D", "[YYYY]",
	}
	formatDates := []string{"1979-01-01", "2000-01-01", "2083-01-01", "2083-06-06", "2083-12-30", "2100-12-31"}
	for _, s := range formatDates {
		d := bs.MustParse(s)
		for _, layout := range layouts {
			f.Format = append(f.Format, formatCase{s, layout, must(d.Format(layout))})
		}
	}

	addDates := []string{"1979-01-01", "1979-01-02", "2079-12-30", "2080-01-01", "2080-06-30", "2083-06-06", "2083-06-31", "2100-12-30", "2100-12-31"}
	offsets := []int{-100000, -44562, -44561, -366, -365, -32, -31, -30, -2, -1, 0, 1, 2, 29, 30, 31, 32, 365, 366, 44561, 44562, 100000}
	for _, s := range addDates {
		d := bs.MustParse(s)
		for _, n := range offsets {
			r, err := d.AddDays(n)
			c := addDaysCase{BS: s, Days: n, Error: errKind(err)}
			if err == nil {
				c.Result = r.String()
			}
			f.AddDays = append(f.AddDays, c)
		}
	}

	for _, a := range addDates {
		for _, b := range addDates {
			f.DaysBetween = append(f.DaysBetween, betweenCase{a, b, must(bs.DaysBetween(bs.MustParse(a), bs.MustParse(b)))})
		}
	}

	for _, s := range []string{"2083-06-06", "0123456789", "०१२३४५६७८९", "no digits here", "", "2083-06-06 has 10 digits: 0123456789", "मिति २०८३-06-०६", "-12.5"} {
		f.Digits = append(f.Digits, digitsCase{s, bs.ToNepaliDigits(s), bs.FromNepaliDigits(s)})
	}

	for month := -1; month <= 13; month++ {
		name, err := bs.MonthName(month)
		nepali, _ := bs.MonthNameNepali(month)
		f.MonthNames = append(f.MonthNames, monthNameCase{month, name, nepali, errKind(err)})
	}

	for _, year := range []int{bs.MinBSYear - 1, bs.MinBSYear, 2000, 2083, 2087, 2096, bs.MaxBSYear, bs.MaxBSYear + 1} {
		d := bs.Date{Year: year, Month: 1, Day: 1}
		start, err := d.StartOfYear()
		c := yearBoundsCase{Year: year, Error: errKind(err)}
		if err == nil {
			c.Start = start.String()
			c.End = must(d.EndOfYear()).String()
		}
		f.YearBounds = append(f.YearBounds, c)
	}

	for _, ym := range [][2]int{{bs.MinBSYear - 1, 12}, {bs.MaxBSYear + 1, 1}, {2083, 0}, {2083, 13}, {2083, -1}} {
		d := bs.Date{Year: ym[0], Month: ym[1], Day: 1}
		_, errStart := d.StartOfMonth()
		_, errEnd := d.EndOfMonth()
		_, errFirst := bs.FirstWeekdayOfMonth(ym[0], ym[1])
		_, errWeeks := bs.WeeksInMonth(ym[0], ym[1])
		_, errCal := bs.MonthCalendar(ym[0], ym[1])
		f.MonthErrors = append(f.MonthErrors, monthErrorCase{ym[0], ym[1], errKind(errStart), errKind(errEnd), errKind(errFirst), errKind(errWeeks), errKind(errCal)})
	}

	// Age: every pair from a set of dates chosen around month ends (where
	// days are borrowed), 32-day months, year ends and both range ends.
	ageDates := []string{
		"1979-01-01", "1990-05-15", "2000-01-30", "2040-03-32", "2060-06-15", "2082-12-30",
		"2083-01-01", "2083-02-31", "2083-03-32", "2083-04-01", "2083-06-06", "2083-06-07",
		"2083-06-31", "2084-01-01", "2084-03-31", "2100-12-31",
	}
	for _, birth := range ageDates {
		for _, today := range ageDates {
			years, months, days, err := bs.Age(bs.MustParse(birth), bs.MustParse(today))
			f.Age = append(f.Age, ageCase{birth, today, years, months, days, errKind(err)})
		}
	}

	return f
}

type monthsFile struct {
	Comment string
	Source  string
	// Months holds one row per supported BS month, in order:
	// [ "YYYY-MM", first weekday, weeks, grid, startOfMonth, endOfMonth, steps ]
	// where grid is MonthCalendar with 0 for empty cells, and steps is a list
	// of [day, NextMonth, PreviousMonth] for days 1, 28 and each of 29-32
	// that exists in the month. A result is "YYYY-MM-DD", or "!" plus the
	// error kind.
	Months []any
}

func stepResult(d bs.Date, err error) string {
	if err != nil {
		return "!" + errKind(err)
	}
	return d.String()
}

func months() monthsFile {
	f := monthsFile{
		Comment: "Generated by tools/go-reference. Each entry: [BS year-month, FirstWeekdayOfMonth (0 = Sunday), WeeksInMonth, MonthCalendar (0 = empty cell), StartOfMonth, EndOfMonth, [[day, NextMonth, PreviousMonth], ...]]. A result starting with ! is a go-bs error kind.",
		Source:  source,
	}
	for year := bs.MinBSYear; year <= bs.MaxBSYear; year++ {
		for month := 1; month <= 12; month++ {
			first := must(bs.FirstWeekdayOfMonth(year, month))
			weeks := must(bs.WeeksInMonth(year, month))
			var grid [][]int
			for _, week := range must(bs.MonthCalendar(year, month)) {
				row := make([]int, len(week))
				for i, cell := range week {
					if cell != nil {
						row[i] = cell.Day
					}
				}
				grid = append(grid, row)
			}
			d := bs.Date{Year: year, Month: month, Day: 1}
			start := must(d.StartOfMonth())
			end := must(d.EndOfMonth())
			var steps [][3]any
			for _, day := range []int{1, 28, 29, 30, 31, 32} {
				if !bs.IsValid(year, month, day) {
					continue
				}
				date := bs.Date{Year: year, Month: month, Day: day}
				next, errNext := date.NextMonth()
				prev, errPrev := date.PreviousMonth()
				steps = append(steps, [3]any{day, stepResult(next, errNext), stepResult(prev, errPrev)})
			}
			f.Months = append(f.Months, []any{fmt.Sprintf("%04d-%02d", year, month), int(first), weeks, grid, start.String(), end.String(), steps})
		}
	}
	return f
}

// writeConversions writes f like writeJSON would, except with one day per
// line: indenting every tuple element onto its own line would roughly
// triple the file's size for no gain in readability.
func writeConversions(path string, f conversionsFile) {
	rows := make([]any, len(f.Days))
	for i, day := range f.Days {
		rows[i] = day
	}
	writeRows(path, f.Comment, f.Source, "days", rows)
}

// writeRows writes a JSON object with $comment, source, count and a key
// holding rows, one row per line.
func writeRows(path, comment, source, key string, rows []any) {
	var b strings.Builder
	header := must(json.Marshal(struct {
		Comment string `json:"$comment"`
		Source  string `json:"source"`
		Count   int    `json:"count"`
	}{comment, source, len(rows)}))
	b.Write(header[:len(header)-1])
	fmt.Fprintf(&b, ",\n%q: [\n", key)
	for i, row := range rows {
		b.Write(must(json.Marshal(row)))
		if i < len(rows)-1 {
			b.WriteByte(',')
		}
		b.WriteByte('\n')
	}
	b.WriteString("]}\n")
	writeFile(path, []byte(b.String()))
}

func writeJSON(path string, v any) {
	data, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		log.Fatal(err)
	}
	writeFile(path, append(data, '\n'))
}

func writeFile(path string, data []byte) {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Println("wrote", path)
}
